// Mosquitto password file + ACL generation (used by `npm run devices:provision` and the tests).
import { pbkdf2Sync, randomBytes } from 'node:crypto';

/**
 * Hash in Mosquitto 2's `$7$` format (PBKDF2-HMAC-SHA512, 101 iterations, 12-byte salt), the same
 * format `mosquitto_passwd` writes.
 */
export function mosquittoPasswordHash(
  password: string,
  salt: Buffer = randomBytes(12),
  iterations = 101,
): string {
  const hash = pbkdf2Sync(password, salt, iterations, 64, 'sha512');
  return `$7$${iterations}$${salt.toString('base64')}$${hash.toString('base64')}`;
}

export interface MqttAccount {
  username: string;
  password: string;
}

export interface DeviceAccount extends MqttAccount {
  patientId: string;
}

export const deviceTopic = (prefix: string, patientId: string, deviceId: string) =>
  `${prefix}/${patientId}/${deviceId}`;

export function buildPasswordFile(accounts: MqttAccount[]): string {
  return accounts.map((a) => `${a.username}:${mosquittoPasswordHash(a.password)}`).join('\n') + '\n';
}

/**
 * Deny by default. The server may only READ device topics (+ broker stats for health checks);
 * each device may only WRITE its own patient's topic.
 */
export function buildAclFile(prefix: string, serverUsername: string, devices: DeviceAccount[]): string {
  const lines = [
    '# Generated by `npm run devices:provision`. Do not edit.',
    `user ${serverUsername}`,
    `topic read ${prefix}/#`,
    'topic read $SYS/#',
    '',
  ];
  for (const d of devices) {
    lines.push(`user ${d.username}`, `topic write ${deviceTopic(prefix, d.patientId, d.username)}`, '');
  }
  return lines.join('\n');
}

export const generatePassword = () => randomBytes(18).toString('base64url');
