// End-to-end over a real Mosquitto broker whose passwd/acl were generated by src/vitals/mosquitto.ts.
import mqtt, { type MqttClient } from 'mqtt';
import { afterAll, beforeAll, beforeEach, describe, expect, inject, it } from 'vitest';
import { Device } from '../src/models/device';
import { Patient } from '../src/models/patient';
import { Village } from '../src/models/village';
import { createVitalsHandler, type MqttIngestor, startMqttIngestor } from '../src/vitals/ingest';
import { deviceTopic, mosquittoPasswordHash } from '../src/vitals/mosquitto';
import { hasDocker, minutesAgo, useTestDb, useVitalsStore } from './helpers';
import { MQTT_TEST } from './mqttFixture';

useTestDb();
const store = useVitalsStore();
const { prefix, server, deviceA, deviceB } = MQTT_TEST;
const topicA = deviceTopic(prefix, deviceA.patientId, deviceA.username);
const topicB = deviceTopic(prefix, deviceB.patientId, deviceB.username);

const connect = (username: string, password: string) =>
  mqtt.connectAsync(inject('mqttUrl'), {
    username,
    password,
    protocolVersion: 5,
    reconnectPeriod: 0,
    connectTimeout: 5000,
  });

async function waitFor<T>(fn: () => Promise<T | null>, timeoutMs = 8000): Promise<T | null> {
  const end = Date.now() + timeoutMs;
  while (Date.now() < end) {
    const v = await fn();
    if (v) return v;
    await new Promise((r) => setTimeout(r, 200));
  }
  return null;
}

describe('mosquittoPasswordHash', () => {
  it('uses the $7$ PBKDF2-SHA512 format', () => {
    expect(mosquittoPasswordHash('secret', Buffer.alloc(12, 1))).toMatch(
      /^\$7\$101\$AQEBAQEBAQEBAQEB\$[A-Za-z0-9+/]{86}==$/,
    );
  });
});

describe.skipIf(!hasDocker())('MQTT ingestion through the real broker', () => {
  let ingestor: MqttIngestor;
  let device: MqttClient;

  // useTestDb() empties the database before every test, so the registry is recreated each time.
  beforeEach(async () => {
    const village = await Village.create({ name: 'Test village', district: 'Test' });
    for (const d of [deviceA, deviceB]) {
      await Patient.create({
        _id: d.patientId,
        name: d.username,
        sex: 'male',
        dateOfBirth: new Date('1970-01-01'),
        villageId: village._id,
      });
      await Device.create({ deviceId: d.username, patientId: d.patientId });
    }
  });

  beforeAll(async () => {
    ingestor = startMqttIngestor({
      url: inject('mqttUrl'),
      ...server,
      topicPrefix: prefix,
      handler: createVitalsHandler({ store: store(), topicPrefix: prefix }),
      log: () => {},
    });
    await waitFor(async () => (ingestor.isConnected() ? true : null));
    await new Promise((r) => setTimeout(r, 300)); // let the subscription settle
    device = await connect(deviceA.username, deviceA.password);
  });

  afterAll(async () => {
    await device?.endAsync();
    await ingestor?.stop();
  });

  it('a device publishing to its own topic gets its reading stored', async () => {
    const ts = new Date();
    await device.publishAsync(topicA, JSON.stringify({ ts: ts.toISOString(), spo2: 96, heartRate: 72 }), {
      qos: 1,
    });
    const latest = await waitFor(() => store().latest(deviceA.patientId, minutesAgo(1), new Date()));
    expect(latest).toMatchObject({ spo2: 96, heartRate: 72 });
  });

  it("ACL: a device cannot publish to another patient's topic", async () => {
    const body = JSON.stringify({ ts: new Date().toISOString(), spo2: 70 });
    // MQTT 5: the broker answers PUBACK with reason code 135 (Not authorized).
    await expect(device.publishAsync(topicB, body, { qos: 1 })).rejects.toMatchObject({ code: 135 });
    await new Promise((r) => setTimeout(r, 1000));
    expect(await store().latest(deviceB.patientId, minutesAgo(5), new Date())).toBeNull();
  });

  it("ACL: a device never receives other patients' vitals", async () => {
    // Mosquitto grants the SUBSCRIBE but the read ACL filters every message out.
    const received: string[] = [];
    device.on('message', (topic) => received.push(topic));
    await device.subscribeAsync(`${prefix}/#`, { qos: 1 });
    const other = await connect(deviceB.username, deviceB.password);
    try {
      await other.publishAsync(topicB, JSON.stringify({ ts: new Date().toISOString(), spo2: 95 }), {
        qos: 1,
      });
      await new Promise((r) => setTimeout(r, 1500));
      expect(received).toEqual([]);
      // ...while the server, which may read vitals, did get it.
      expect(await store().latest(deviceB.patientId, minutesAgo(1), new Date())).toMatchObject({ spo2: 95 });
    } finally {
      await other.endAsync();
    }
  });

  it('ACL: the server account can read but not publish vitals', async () => {
    const serverClient = await connect(server.username, server.password);
    try {
      await expect(
        serverClient.publishAsync(topicA, JSON.stringify({ ts: new Date().toISOString(), spo2: 99 }), {
          qos: 1,
        }),
      ).rejects.toMatchObject({ code: 135 });
    } finally {
      await serverClient.endAsync();
    }
  });

  it.each([
    ['a wrong password', deviceA.username, 'nope'],
    ['an unknown user', 'intruder', 'x'],
  ])('rejects %s', async (_name, user, pass) => {
    await expect(connect(user, pass)).rejects.toThrow();
  });

  it('rejects anonymous clients', async () => {
    await expect(
      mqtt.connectAsync(inject('mqttUrl'), { protocolVersion: 5, reconnectPeriod: 0, connectTimeout: 5000 }),
    ).rejects.toThrow();
  });
});
