// Writes MQTT credentials for every active device. Called by the seed (one-step setup) and by
// `npm run devices:provision`. Mosquitto's entrypoint watches these files and reloads (SIGHUP) by
// itself; the simulator reconnects when devices.json changes.
import { mkdirSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { Env } from '../config/env';
import { ageInMonths } from '../lib/dates';
import { Device } from '../models/device';
import { Patient } from '../models/patient';
import { buildAclFile, buildPasswordFile, deviceTopic, generatePassword } from '../vitals/mosquitto';

/**
 * Write to a temp file, then rename: Mosquitto never reads a half-written file, and replacing a file
 * created by another container user (e.g. root in the Mosquitto container) only needs write
 * permission on the folder.
 */
function writeAtomic(path: string, content: string) {
  const tmp = `${path}.${process.pid}.tmp`;
  writeFileSync(tmp, content);
  renameSync(tmp, path);
}

export interface ProvisionResult {
  devices: { deviceId: string; patientName: string | null; topic: string }[];
  files: string[];
}

export async function provisionDevices(
  env: Pick<
    Env,
    | 'MQTT_USERNAME'
    | 'MQTT_PASSWORD'
    | 'MQTT_TOPIC_PREFIX'
    | 'MQTT_URL'
    | 'MQTT_PROVISION_DIR'
    | 'SIMULATOR_DEVICES_FILE'
  >,
): Promise<ProvisionResult> {
  if (!env.MQTT_PASSWORD) {
    throw new Error('MQTT_PASSWORD (the server account) is not set; it must match infra/.env.');
  }
  const devices = await Device.find({ active: true }).sort({ deviceId: 1 }).lean();
  const patients = new Map(
    (await Patient.find({ _id: { $in: devices.map((d) => d.patientId) } }).lean()).map((p) => [
      String(p._id),
      p,
    ]),
  );
  const accounts = devices.map((d) => ({
    username: d.deviceId,
    password: generatePassword(),
    patientId: String(d.patientId),
  }));

  const dir = resolve(env.MQTT_PROVISION_DIR);
  mkdirSync(dir, { recursive: true });
  const passwdFile = resolve(dir, 'passwd');
  const aclFile = resolve(dir, 'acl');
  const devicesFile = resolve(env.SIMULATOR_DEVICES_FILE);
  mkdirSync(dirname(devicesFile), { recursive: true });

  const summary = accounts.map((a) => {
    const patient = patients.get(a.patientId);
    return {
      deviceId: a.username,
      username: a.username,
      password: a.password,
      patientId: a.patientId,
      patientName: patient?.name ?? null,
      ageYears: patient ? Math.floor(ageInMonths(patient.dateOfBirth) / 12) : null,
      topic: deviceTopic(env.MQTT_TOPIC_PREFIX, a.patientId, a.username),
    };
  });

  // devices.json first: when Mosquitto reloads, the simulator already has the new passwords.
  writeAtomic(
    devicesFile,
    JSON.stringify(
      {
        notes: 'Generated by the seed / `npm run devices:provision`. Contains MQTT passwords: do not commit.',
        brokerUrl: env.MQTT_URL ?? 'mqtt://localhost:1883',
        topicPrefix: env.MQTT_TOPIC_PREFIX,
        generatedAt: new Date().toISOString(),
        devices: summary,
      },
      null,
      2,
    ) + '\n',
  );
  writeAtomic(aclFile, buildAclFile(env.MQTT_TOPIC_PREFIX, env.MQTT_USERNAME, accounts));
  writeAtomic(
    passwdFile,
    buildPasswordFile([{ username: env.MQTT_USERNAME, password: env.MQTT_PASSWORD }, ...accounts]),
  );

  return {
    devices: summary.map(({ deviceId, patientName, topic }) => ({ deviceId, patientName, topic })),
    files: [passwdFile, aclFile, devicesFile],
  };
}
