// Usage: npm run devices:provision -w @ruralcare/server     (reads server/.env)
//
// Generates fresh MQTT credentials for every active device (created by the seed) and writes:
//   - <MQTT_PROVISION_DIR>/passwd  Mosquitto password file (server account + one per device)
//   - <MQTT_PROVISION_DIR>/acl     ACL: server reads all vitals; each device writes only its patient's topic
//   - <SIMULATOR_DEVICES_FILE>     credentials + topics for the edge simulator (git-ignored)
// Then restart the broker so it reloads the files.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import mongoose from 'mongoose';
import { loadEnv } from '../config/env';
import { connectDb } from '../db';
import { ageInMonths } from '../lib/dates';
import { Device } from '../models/device';
import { Patient } from '../models/patient';
import { buildAclFile, buildPasswordFile, deviceTopic, generatePassword } from '../vitals/mosquitto';

const env = loadEnv();
if (!env.MQTT_PASSWORD) {
  console.error('Set MQTT_PASSWORD (the server account) in server/.env first; it must match infra/.env.');
  process.exit(1);
}

await connectDb(env.MONGO_URI);
const devices = await Device.find({ active: true }).sort({ deviceId: 1 }).lean();
const patients = new Map(
  (await Patient.find({ _id: { $in: devices.map((d) => d.patientId) } }).lean()).map((p) => [
    String(p._id),
    p,
  ]),
);
await mongoose.disconnect();

if (!devices.length) {
  console.error('No active devices. Run the seed first: npm run seed -w @ruralcare/server');
  process.exit(1);
}

const accounts = devices.map((d) => ({
  username: d.deviceId,
  password: generatePassword(),
  patientId: String(d.patientId),
}));

const provisionDir = resolve(env.MQTT_PROVISION_DIR);
mkdirSync(provisionDir, { recursive: true });
writeFileSync(
  resolve(provisionDir, 'passwd'),
  buildPasswordFile([{ username: env.MQTT_USERNAME, password: env.MQTT_PASSWORD }, ...accounts]),
);
writeFileSync(resolve(provisionDir, 'acl'), buildAclFile(env.MQTT_TOPIC_PREFIX, env.MQTT_USERNAME, accounts));

const simulatorFile = resolve(env.SIMULATOR_DEVICES_FILE);
mkdirSync(dirname(simulatorFile), { recursive: true });
writeFileSync(
  simulatorFile,
  JSON.stringify(
    {
      notes: 'Generated by `npm run devices:provision`. Contains MQTT passwords: do not commit.',
      brokerUrl: env.MQTT_URL ?? 'mqtt://localhost:1883',
      topicPrefix: env.MQTT_TOPIC_PREFIX,
      generatedAt: new Date().toISOString(),
      devices: accounts.map((a) => {
        const patient = patients.get(a.patientId);
        return {
          deviceId: a.username,
          username: a.username,
          password: a.password,
          patientId: a.patientId,
          patientName: patient?.name ?? null,
          ageYears: patient ? Math.floor(ageInMonths(patient.dateOfBirth) / 12) : null,
          topic: deviceTopic(env.MQTT_TOPIC_PREFIX, a.patientId, a.username),
        };
      }),
    },
    null,
    2,
  ) + '\n',
);

console.log(`Provisioned ${accounts.length} devices:`);
console.table(
  accounts.map((a) => ({
    device: a.username,
    patient: patients.get(a.patientId)?.name,
    topic: deviceTopic(env.MQTT_TOPIC_PREFIX, a.patientId, a.username),
  })),
);
console.log(`Wrote ${resolve(provisionDir, 'passwd')}, ${resolve(provisionDir, 'acl')} and ${simulatorFile}`);
console.log('Next: docker compose -f infra/docker-compose.yml restart mosquitto');
console.log('      docker compose -f infra/docker-compose.yml --profile edge up -d edge-simulator');
